[package]
name = "libchafa"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.72.1"
convert_case = "0.8.0"
pkg-config = "0.3.32"

[dependencies]
bitflags = "2.9.4"

[features]
ffi = []
